version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: crawler_worker
    command: celery -A app.tasks worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis

  beat:
    build: .
    container_name: crawler_beat
    command: celery -A app.tasks beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
